name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^2.2.0
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  cupertino_icons: ^0.1.2
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.2

flutter:
  uses-material-design: true

  assets:
  - images/
